services:
  web:
    volumes:
      - '../../../app:/opt/node_app/app'
      - '../../../lib:/opt/node_app/lib'
      - '../../../views:/opt/node_app/views'
      - '../../../public:/opt/node_app/public'
      - '../../../extensions:/opt/node_app/extensions'
      - '../../../db:/opt/node_app/db'
      - '../../../certs:/opt/node_app/certs'
      - '../../../uploads:/opt/node_app/uploads:rw'
    ports:
      - '8100:3000'
    restart: 'always'
    stdin_open: true
    tty: true
    build:
      context: '../../../'
      dockerfile: '.wappler/targets/Development/web/Dockerfile'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    depends_on:
      - 'db'
  db:
    image: 'postgres:16.6'
    environment:
      POSTGRES_PASSWORD: 'FulJk7PR'
      POSTGRES_USER: 'db_user'
      POSTGRES_DB: 'pense_saas'
    volumes:
      - './db_init:/docker-entrypoint-initdb.d'
    ports:
      - '9906:5432'
    restart: 'always'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
volumes: {}
