services:
  db:
    environment:
      POSTGRES_PASSWORD: 'FulJk7PR'
      POSTGRES_USER: 'db_user'
      POSTGRES_DB: 'pense_saas'
    volumes:
      - 'db-volume:/var/lib/postgresql/data'
    ports:
      - '9906:5432'
    restart: 'always'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    build:
      context: '.'
      dockerfile: 'db/Dockerfile'
  web:
    depends_on:
      - 'db'
    ports:
      - '80:3000'
    restart: 'always'
    stdin_open: true
    tty: true
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    build:
      context: '../../../'
      dockerfile: '.wappler/targets/Production/web/Dockerfile'
    volumes:
      - 'user_uploads:/opt/node_app/uploads:rw'
volumes:
  db-volume: ~
  user_uploads: ~
